[build]
  base = "frontend"
  publish = "build"
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"

[build.environment]
  NODE_VERSION = "18.20.0"
  NPM_FLAGS = "--legacy-peer-deps --force"
  CI = "true"
  NODE_ENV = "production"
  DISABLE_ESLINT_PLUGIN = "true"
  GENERATE_SOURCEMAP = "false"
  SKIP_PREFLIGHT_CHECK = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31560000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"

[context.deploy-preview]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"

[context.branch-deploy]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
