[build]
  base = "frontend"
  publish = "build"
  command = "npm install --legacy-peer-deps --force && npm run build:simple"

[build.environment]
  NODE_VERSION = "24.5.0"
  NPM_FLAGS = "--legacy-peer-deps --force"
  CI = "false"
  NODE_ENV = "production"
  DISABLE_ESLINT_PLUGIN = "true"
  GENERATE_SOURCEMAP = "false"
  SKIP_PREFLIGHT_CHECK = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31560000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm install --legacy-peer-deps --force && npm run build:simple"

[context.deploy-preview]
  command = "npm install --legacy-peer-deps --force && npm run build:simple"

[context.branch-deploy]
  command = "npm install --legacy-peer-deps --force && npm run build:simple"
