[build]
buildCommand = "cd backend && PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci --only=production --no-audit --no-fund"

[deploy]
startCommand = "cd backend && npm start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
NODE_ENV = "production"
