services:
  - type: web
    name: aijobchommie-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"
    plan: free
    region: oregon
    buildFilter:
      paths:
        - backend/**
        - render.yaml
