services:
  - type: web
    name: aijobchommie-backend
    runtime: node
    buildCommand: |
      cd backend &&
      npm ci --only=production --no-audit --no-fund
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome"
    plan: free
    region: oregon
    buildFilter:
      paths:
        - backend/**
        - render.yaml
