services:
  - type: web
    name: aijobchommie-backend
    runtime: node
    rootDir: backend
    buildCommand: npm ci --production --no-audit --no-fund && echo "Puppeteer will use system Chrome"
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"
      - key: NPM_CONFIG_AUDIT
        value: "false"
      - key: NPM_CONFIG_FUND
        value: "false"
    plan: free
    region: oregon
    buildFilter:
      paths:
        - backend/**
        - render.yaml
