services:
  - type: web
    name: aijobchommie-backend
    runtime: node
    buildCommand: |
      export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true &&
      export PUPPETEER_SKIP_DOWNLOAD=true &&
      export PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable &&
      npm ci --only=production --no-audit --no-fund
    startCommand: node src/index.js
    healthCheckPath: /api/health
    rootDirectory: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"
      - key: RENDER
        value: "true"
    plan: free
    region: oregon
    buildFilter:
      paths:
        - backend/**
        - render.yaml
